- helfi_tpr.info.yml
- helfi_tpr.install
- src/Entity/Form/ContentEntityForm.php
- src/Entity/Unit.php
- tests/src/Functional/MigrationTestBase.php
- tests/src/Functional/UnitMenuLinkTest.php
- tests/src/Kernel/MigrationTestBase.php
`composer update drupal/helfi_api_base`
`composer require drupal/helfi_tpr:dev-UHF-1526`
Make sure menu links can be added straight from the unit page.
> UHF-1526: Allow menu links to be added from entity forms

- helfi_tpr.tokens.inc
This PR introduces a new custom token that can be used for generating URL aliases for `tpr_unit` and `tpr_service` entities. It works like the default `[node:menu-link:parents:join-path]` token for nodes, appending the menu parents before the entity label in the URL alias. The needed configuration and testing instructions are in `drupal-helfi` repo: https://github.com/City-of-Helsinki/drupal-helfi/pull/134
> UHF-1621: TPR custom URL alias

- config/install/system.action.tpr_errand_service_publish_action.yml
- config/install/system.action.tpr_errand_service_unpublish_action.yml
- config/install/system.action.tpr_service_channel_publish_action.yml
- config/install/system.action.tpr_service_channel_unpublish_action.yml
- config/language/fi/views.view.tpr_errand_service_list.yml
- config/language/fi/views.view.tpr_service_channel_list.yml
- config/optional/views.view.tpr_errand_service_list.yml
- config/optional/views.view.tpr_service_channel_list.yml
- helfi_tpr.install
- tests/src/Functional/ErrandServiceListTest.php
- tests/src/Functional/ListTestBase.php
- tests/src/Functional/ServiceChannelListTest.php
- tests/src/Functional/UnitListTest.php
Testing:
* If you don't already have a site for testing, create one:
* `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-main hel-platform --no-interaction --repository https://repository.drupal.hel.ninja/`
* cd hel-platform
* make new
* Update the module to include changes: `composer require drupal/helfi_tpr:dev-UHF-1772-missing-integration-overviews`
* Run `drush updb`
* Make sure you have imported some "Errand service" and "Service channel" content. If not, run:
* `drush migrate:import tpr_errand_service`
* `drush migrate:import tpr_service_channel`
* As an anonymous user, go to the pages `/admin/content/integrations/tpr-errand-service` and `admin/content/integrations/tpr-service-channel`. You should **not** see any content.
* As an admin user (for testing purposes, …
> UHF-1772 Missing integration overviews

- helfi_tpr.links.task.yml
- src/Entity/Channel.php
- src/Entity/ErrandService.php
- src/Entity/TprEntityBase.php
- tests/src/Kernel/ChannelEntityTest.php
- tests/src/Kernel/ErrandServiceEntityTest.php
- tests/src/Kernel/ServiceEntityTest.php
- tests/src/Kernel/UnitEntityTest.php
How to test:
* If you don't already have a site for testing, create one:
* `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-main hel-platform --no-interaction --repository https://repository.drupal.hel.ninja/`
* `cd hel-platform`
* `make new`
* Enable the module: `drush en -y helfi_tpr`
* Update the module to include changes: `composer require drupal/helfi_tpr:dev-UHF-1740-prevent-deletions`
*  Clear caches: `drush cr`
* Check that deleting TPR entities (especially Errand services and Service channels) is no longer possible using the admin UI: there are no "Delete" links.
* One way to check that TPR entities are not deleted during the import is to temporarily change the `MAX_SYNC_ATTEMPTS` constant at `TprEntityBase` to 1. Then running the import with a not yet …
> UHF-1740 Prevent deletions

- migrations/tpr_unit.yml
- src/Entity/Unit.php
- templates/tpr-unit.html.twig
Adds missing email and link ("Elsewhere on the web") to TPR Unit pages.
How to test
* Choose which site to test: drupal-helfi-sote, drupal-helfi-kymp, drupal-helfi-strategia or drupal-helfi.
* Checkout branch named `UHF-2014-missing-email-links` from the site repository.
* Get changes to TPR module: `composer require drupal/helfi_tpr:dev-UHF-2014_missing_email`
* Get changes to platform config `composer require drupal/helfi_platform_config:dev-UHF-2014-missing-email-links`
* Using `make shell`:
* Import configs: `drush cim`
* Import locales: `drush locale-import fi /app/public/modules/contrib/helfi_platform_config/translations/fi/strings.po`
* Clear caches: `drush cr`
* Migrate some TPR Units: `MIGRATE_LIMIT=50 drush migrate:import tpr_unit`
* From the newly migrated Units, find a one …
> UHF-2014 Missing email and link

- helfi_tpr.install
- migrations/tpr_unit.yml
- src/Entity/Unit.php
- src/Fixture/Unit.php
- tests/src/Kernel/UnitMigrationTest.php
How to test (in a working environment):
- checkout this branch: `composer require drupal/helfi_tpr:dev-UHF-1717_palvelukielet`
- run `drush updb`
- import some TPR units and see the new imported data from the database (`tpr_unit__provided_languages` table)
- optionally, you can set the `Provided languages` field visible temporarily in the UI
> UHF-1717: TPR unit provided languages

- templates/tpr-unit.html.twig
Removes the "Elsewhere on the web" element from TPR Unit page.
Test:
1. Select one of the websites which uses helfi_tpr module (or  run "drush en -y helfi_tpr" inside container)
2. Import some TPR unit entities "MIGRATE_LIMIT=20 drush mim tpr_unit"
- At this point you might want to check which units contain the "elsewhere on web" element for future reference.
3. Get changes to TPR module: "composer require drupal/helfi_tpr:dev-UHF-2516_remove_elsewhere_element"
4. Run "drush cr" inside container (should be enough with this small feature)
5. Go check the TPR unit page which used to have "elsewhere on web" element. The element should be gone.
> Removed elsewhere on the web element

- config/rewrite/pathauto.settings.yml
The config rewrite prevents using helfi_tpr module as dependency.
The removed config rewrite is implemented at helfi_tpr_config module: helfi_tpr_config_update_9002.
> UHF-833: Remove obsolete config rewrite

- src/Entity/Service.php
Sets TPR Service's errand_services field translatable to fix the disappearing errand service references.
How to test:
* If you don't already have a site for testing, create one:
* `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-main hel-platform --no-interaction --repository https://repository.drupal.hel.ninja/`
* `cd hel-platform`
* `make new`
* Enable TPR module and configs: (using `make shell`):`drush en -y helfi_tpr helfi_tpr_config`
* First, import TPR content before applying the change (using `make shell`):
* `drush migrate:import tpr_errand_service`
* `drush migrate:import tpr_service`
* `drush migrate:import tpr_service_channel`
* Use the TPR service with ID 4093 (`/fi/tpr-service/4093`) as an example, since currently its Finnish version contains Errand …
> UHF-2506: Set TPR Service's errand_services field translatable

- helfi_tpr.module
How to set up:
- Run SOTE instance
- Check out this branch of the module: `composer require drupal/helfi_tpr:dev-UHF-405_provided_languages_variable`
- Clear caches: `make drush-cr`
- There should now be a `provided_languages` array variable available in the TPR unit template
> UHF-405: provided_languages variable for the template

- templates/tpr-service.html.twig
- templates/tpr-unit.html.twig
How to test:
1. Require this branch to any instance you are running: `composer require drupal/helfi_tpr:dev-UHF-2500_change_print_order_on_service_and_unit`
2. If you don't have any units, services, errand services or service channels imported then you need to do that. 
* `make shell`
* Enable TPR module with configuration `drush en -y helfi_tpr_config`
* Import units `MIGRATE_LIMIT=500 drush mim tpr_unit`
* Import services `drush mim tpr_service`
* Import errand servives `drush mim tpr_errand_service`
* Import service channels `drush mim tpr_service_channel`
* `drush cr`
* `drush uli` and log into the site using the link.
3. Go to edit any unit that has a map in it (most of them have) and add some text to the "Upper content region". Save the unit and go view it.
4. The "Upper content …
> UHF-2500: Change the print order on tpr service and tpr unit

- helfi_tpr.module
- src/Entity/Form/ContentEntityForm.php
- tests/src/Functional/ServiceMenuLinkTest.php
- tests/src/Functional/ServiceTranslationTest.php
- tests/src/Functional/UnitMenuLinkTest.php
- tests/src/Functional/UnitTranslationTest.php
How to test:
- Checkout this branch of the module: `composer require drupal/helfi_tpr:dev-UHF-2103_tpr_entity_form_redirect`
- Edit any TPR Unit or Service entity and save
- See how the browser redirects to the entity page and a confirmation message is displayed
> UHF-2103: Redirect & confirmation message when editing TPR Unit or Service entities

- templates/tpr-unit.html.twig
[UHF-405](https://helsinkisolutionoffice.atlassian.net/browse/UHF-405)
* Added the "Service in Swedish" tag to unit, teaser, teaser with image (but not to teaser wide, because Elina asked not to)
- Run SOTE instance
- Check out this branch of the module: `composer require drupal/helfi_tpr:dev-UHF-405_unit_service_in_lang_sv`
- Clear caches: `make drush-cr`
- There should now be a Service in Swedish text on the unit page, teaser and teaser with image
- Check this together with the related [hdbt PR](https://github.com/City-of-Helsinki/drupal-hdbt/pull/153) to see the styling.
Related: [HDBT PR](https://github.com/City-of-Helsinki/drupal-hdbt/pull/153)
> UHF-405: Add supports Swedish data to template

- templates/tpr-service.html.twig
How to set up for testing:
- Set up a local environment
- Checkout this branch of the TPR module: `composer require drupal/helfi_tpr:dev-UHF-2509_tpr_service_links`
- Checkout the corresponding branch of the HDBT theme: `composer require drupal/helfi_hdbt:dev-UHF-2509_tpr_service_links`
- If the above doesn't work, try the following (it may not work as there is no PR made of the branch):
- `cd public/themes/contrib/hdbt`
- `git fetch`
- `git checkout UHF-2509_tpr_service_links`
- Import some TPR Services (if not already):
- `make shell`
- `drush mim tpr_service` 
- Clear cache: `make drush-cr`
- Access any TPR Service with links (for example "Asukaspysäköinti", ID 3621) → see the links in the sidebar
> UHF-2509: TPR Service links

- helfi_tpr.tokens.inc
Fixes the service entity paths.
Start with any existing environment (preferably with existing database)
1. If you you don't have existing test/prod environment database:
- (just get the database, it makes this easier and faster and skip this first step)
- import bunch of services, 
- assign them to menu, remember the translations as well, 
- publish the entities,  
- run the bulk update for paths to break the paths.
- Go check some of the paths for different service entity translations. The translations should be wrong.
2. If you use existing database, run "make fresh".
3. Run "composer require drupal/helfi_tpr:dev-UHF-2838_path_translation_fix"
4. Running "make drush-cr" should be enough at this point. Also make sure there are published service and service translations in database and …
> UHF-2838 fixed service path translations

- src/Plugin/migrate/source/ServiceRegister.php
There was a problem when importing services.
Assuming there was an existing service entity in Finnish with translations in Swedish and English. Then, if fetching the Finnish source data, for some reason, failed, the English version became the default one. This caused the Finnish version to disappear from the UI, as it was no longer included with the latest revision.
At this point, the English version had the entity references which were previously added to the Finnish version.
After this, when re-importing the service without failing to get the data, the Finnish version became once again the default language version. Now there were all three language versions, but the English translation had lost all its previously added entity references.
**How to test**
* Set up a local environment.
* …
> UHF-2834: Always use Finnish as service's default language

- .github/workflows/ci.yml
- composer.json
- helfi_tpr.install
- migrations/tpr_errand_service.yml
- migrations/tpr_service.yml
- src/Field/Connection/OpeningHour.php
- src/Fixture/ErrandService.php
- src/Fixture/Service.php
- src/Plugin/migrate/destination/Service.php
- src/Plugin/migrate/source/ServiceChannel.php
- src/Plugin/migrate/source/ServiceMap.php
- src/Plugin/migrate/source/ServiceRegister.php
- src/Plugin/migrate/source/TprSourceBase.php
- src/Plugin/migrate/source/Unit.php
- tests/fixtures/service.json
- tests/src/Functional/ListTestBase.php
- tests/src/Functional/ServiceListTest.php
- tests/src/Functional/UnitListTest.php
- tests/src/Kernel/ErrandServiceMigrationTest.php
- tests/src/Kernel/MigrationTestBase.php
- tests/src/Kernel/ServiceMigrationTest.php
- tests/src/Kernel/UnitMigrationTest.php
The `Row->changed()` check has been broken for quite a while already, making migrations to update entities even when there are no new changes.  This should massively speed up any subsequent migrations and make `PARTIAL_MIGRATE` functionality pretty much obsolete.
At the moment unit ids are saved three times (once for every translation).
I made a small service that aggregates TPR service and errand service data into a big JSON dump. Currently every instance makes ~2000 requests per migration to TPR's service endpoint. This should speed up both service migrations by eliminating need to create three requests per entity (one for each language).
See: https://github.com/City-of-Helsinki/drupal-tpr-aggregator
To test this:
- `drush updb`
- `drush cr`
- Run all migrations: `drush mim tpr_unit`, …
> UHF-2908: Fix partial migrates

- helfi_tpr.views_execution.inc
Using the `name_override` field as a default for sorting. If that field is empty, use the `name` field.
To enable correct sorting of names with Scandinavian characters, see this PR: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/214
How to test:
1. Set up SOTE instance & checkout this branch of the module: `composer require drupal/helfi_tpr:dev-UHF-2528_unit_search_sorting`
2. Import some TPR Units
2.1 `make shell`
2.2 `MIGRATE_LIMIT=100 drush mim tpr_unit`
3. Publish some (or all) of the units
4. Create a content page and add Unit search paragraph with some units
5. See how the units are sorted alphabetically by title
6. Edit one of the units and change the `Override: name` to something else
7. See the page with the unit search again and see how the list is ordered …
> UHF-2528: unit_search view sorting alter

- helfi_tpr.views_execution.inc
Similar fix for Service units view as this PR is for Unit search: https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/75
How to test:
- Set up SOTE instance and checkout this branch: `composer require drupal/helfi_tpr:dev-UHF-2528_service_unit_list_sorting`
- Import TPR Services: `drush mim tpr_service` and some TPR Units `MIGRATE_LIMIT=100 drush mim tpr_unit`
- Publish all of the imported TPR Units to make them visible on the TPR Service pages
- Find a TPR Service that has some of the published TPR Units (for example TPR Service ID 7341 should have libraries listed)
- See how the units are sorted alphabetically by title under "Palvelupaikat"
- Edit one of the units and change the `Override: name` to something else
- See the service page with the unit list again and see how …
> UHF-2528: sorting fix also for service_units view

- helfi_tpr.views_execution.inc
How to test:
- Set up SOTE instance
- Checkout this branch of the module: `composer require drupal/helfi_tpr:dev-UHF-3254_unit_list_view_collation_alter`
- Import some TPR Units
- `make shell`
- `MIGRATE_LIMIT=100 drush mim tpr_unit`
- Publish some (or all) of the units
- Create a content page and add Unit search paragraph with some units starting that have Å, Ö or Ä as the first letter of their name (Åggelby, Östersundom, etc.), OR edit some units and make their "Override: Name" start with one of those letters
- See how the units are sorted alphabetically by title
> UHF-3254: unit search/list view collation alter

- config/install/language.content_settings.tpr_ontology_word_details.tpr_ontology_word_details.yml
- config/schema/helfi_tpr.schema.yml
- helfi_tpr.install
- helfi_tpr.links.menu.yml
- helfi_tpr.links.task.yml
- helfi_tpr.module
- migrations/tpr_ontology_word_details.yml
- src/Entity/Form/ContentEntityForm.php
- src/Entity/OntologyWordDetails.php
- src/Plugin/Field/FieldFormatter/SchoolDetailsFormatter.php
- src/Plugin/Field/FieldType/SchoolDetailsItem.php
- src/Plugin/migrate/destination/OntologyWordDetails.php
- src/Plugin/migrate/process/PublishByUnit.php
- src/Plugin/migrate/source/OntologyWordDetails.php
- src/Plugin/views/filter/EducationalMission.php
- src/Plugin/views/filter/Emphasis.php
- src/Plugin/views/filter/OntologyWordDetailsBase.php
- templates/tpr-ontology-word-details-form.html.twig
- templates/tpr-ontology-word-details.html.twig
- templates/tpr-school-details.html.twig
- tests/src/Functional/ServiceRevisionTest.php
- tests/src/Functional/UnitListTest.php
- tests/src/Functional/UnitRevisionTest.php
- tests/src/Kernel/MigrationTestBase.php
- tests/src/Kernel/OntologyWordDetailsTest.php
Adds import for "ontology word details" and adds a new entity "OntologyWordDetails" for them. When these are imported, they are automatically published if the relevant Unit entity is also published.
For now, these are only used to get information high school search filtering.
**How to test:**
* Setup up Kasko development environment.
* Check out Kasko branch `UHF-2604-kasko-ontology_word_details`.
* Get the changes for this module: `composer require drupal/helfi_tpr:dev-UHF-2604-ontology_word_details`
* Run database updates: `drush updb`
* Import configs: `drush cim`
* Clear caches: `drush cr`
* Make sure you have imported tpr_units including Helsinki's upper secondary schools (you can use [this](https://www.hel.fi/helsinki/fi/kasvatus-ja-koulutus/lukiot/opiskelu/lukioiden-painotukset/) …
> UHF-2604: Ontology word details

- config/schema/helfi_tpr.schema.yml
- helfi_tpr.install
- helfi_tpr.module
- helfi_tpr.services.yml
- modules/helfi_school_addons/config/schema/helfi_school_addons.schema.yml
- modules/helfi_school_addons/helfi_school_addons.module
- modules/helfi_school_addons/src/Plugin/views/filter/SchoolDetailsBase.php
- modules/helfi_school_addons/src/Plugin/views/filter/StudyProgrammeType.php
- src/Fixture/OntologyWordDetails.php
- src/Plugin/Field/FieldType/SchoolDetailsItem.php
- src/Plugin/migrate/source/OntologyWordDetails.php
- tests/src/Kernel/OntologyWordDetailsMigrationTest.php
- tests/src/Traits/TprMigrateTrait.php
Adds filter for study programme type (general studies / adult education) which is used with the high school search. The `tpr_ontology_word_details` migration is modified to include relevant ontlogy word details.
**How to test:**
* Setup up Kasko development environment.
* Check out Kasko branch `UHF-3449-kasko-study-programme`.
* Get the changes for this module: `composer require drupal/helfi_tpr:dev-UHF-3449-general-or-adults-filter`.
* Get changes to translations: `composer require drupal/helfi_platform_config:dev-UHF-3449-study-programme-translations`.
* Import configs: `drush cim`.
* Run database update: `drush updb`.
* Clear caches: `drush cr`.
* Import translations:
- `drush locale-import fi /app/public/modules/contrib/helfi_platform_config/translations/fi/strings.po`.
- `drush …
> UHF-3449: Add filter for study programme type

- helfi_tpr.links.task.yml
- src/Entity/Channel.php
- src/Entity/ErrandService.php
To test this:
- `composer require drupal/helfi_tpr:dev-UHF-3691` 
- `drush cr`
What to test:
- Errand service and service channel canonical URLs are not accessible anymore (404)
- You can still edit them through edit form
- Both entities are still shown via entity reference field display
> UHF-3691: Removed canonical route from TPR service channel and errand service entities

- helfi_tpr.views_execution.inc
- src/Entity/Channel.php
- src/Entity/ErrandService.php
- src/Entity/OntologyWordDetails.php
- src/Entity/Service.php
- src/Entity/Unit.php
- src/Plugin/views/filter/Status.php
- src/TprViewsData.php
Ticket: https://helsinkisolutionoffice.atlassian.net/browse/UHF-4643
This adds a new custom views filter for all TPR entities that filters out unpublished entities if the current user doesn't have permissions to view them. Depends on the permissions being named something like `view unpublished [tpr_entity_id]`.
Doesn't include any configuration changes yet for any views.
* Make sure you have an up-to-date instance:
* `make fresh` 
* `composer require drupal/helfi_tpr:dev-UHF-4643-unpublished-services`
* Edit one of the views that concerns TPR entities, for example: /admin/structure/views/view/tpr_unit_list
* Add a new filter and find the new one, which should be called: "Published status or admin user" or "Julkaisutila tai ylläpitokäyttäjä"
* Remove the "view …
> UHF-4643: Custom views filter for unpublished TPR entities

- helfi_tpr.module
Moved `provided_languages` functionality to a SOTE specific custom module: https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/350
> UHF-3166: removed provided_languages functionality

- modules/helfi_address_search/src/Plugin/views/area/AddressSearchInfo.php
Small adjustments to the daycare search styling
* Added two required classes for address not found information.
* Check the hdbt PR.
* Check the hdbt PR.
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/283
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/129
> UHF-4532: Small adjustments to the daycare search styling

- helfi_tpr.install
- src/Entity/OntologyWordDetails.php
This caused error when importing configs: "Unexpected error during import (–––): The readonly_field_widget plugin does not exist".
* Check https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/134 for instructions.
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/134
> Remove readonly_field_widget from view display options

- src/Plugin/views/filter/ProvidedLanguages.php
Use correct provided languages views filter option.
Check instructions from https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/144.
> Fix provided languages views filter option

- helfi_tpr.module
- src/Plugin/views/relationship/TagOwdRelationship.php
- src/TprViewsData.php
Groups daycare search results to avoid duplicate rows.
* When using this specific relationship with views, the views query is tagged and later altered to group by `id` column.
* This removes duplicate result rows caused by joining the `tpr_ontology_word_details_field_data` table.
* Make sure your instance is up and running.
* Update the TPR module:
* `composer require drupal/helfi_tpr:dev-UHF-5473-fix-daycare-search-same-results`
* Navigate to a page containing daycare search.
* Test that:
* duplicate entries are removed.
* other units are not missing.
* pagination still works.
* results are still sorted correctly.
* filters still work.
* address search still works.
* translated versions of the search page are also working.
> UHF-5473: Group daycare search results to avoid duplicate rows

- templates/tpr-service.html.twig
* Removed sidebar content and lower content from tpr-service.html.twig as these fields will be render in sidebar and lower_content blocks
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/292
* https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/366
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/148
* https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/64
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/315
> UHF-2976: Clean regions

- .sonarcloud.properties
- helfi_tpr.install
- migrations/tpr_unit.yml
- src/Entity/Unit.php
- src/Field/Connection/Highlight.php
- src/Field/Connection/Repository.php
- src/Fixture/Unit.php
- src/Plugin/migrate/process/ArrayElementEquals.php
- tests/src/Functional/ConnectionFormatterTest.php
- tests/src/Functional/CustomFieldFormatterTestBase.php
- tests/src/Kernel/UnitMigrationTest.php
- tests/src/Unit/ConnectionRepositoryTest.php
- tests/src/Unit/ConnectionTest.php
Import Highlight connections so that they can be used with unit contact cards.
* Added Highlight field to TPR Units.
* Added Highlight connection.
* Import highlight connections to the new highlight field.
* Also needed to change how the Opening hours connections are imported at the migration config. When the highlight connection was added to the connection repository, the connections source includes both opening hours and hightlights, and this caused the `skip_on_value` process to skip unit rows.
* Update the Helfi TPR module:
* `composer require drupal/helfi_tpr:dev-UHF-5512-tpr-unit-highlights`
* Run `make drush-updb`
* Run `make shell` and the import TPR units:
* `drush migrate:import tpr_unit`
* …
> UHF-5512: Add highlight connection support for TPR Units

- config/install/language.content_settings.tpr_ontology_word_details.tpr_ontology_word_details.yml
* Added missing language content config for tpr_ontology_word_details.
* Now, when installing the module, there is no more missing translation created ja translation changed fields.
* Also, there is no longer an error "InvalidArgumentException: The timestamp must be numeric." when listing the tpr_ontology_word_details items.
* Check https://github.com/City-of-Helsinki/drupal-helfi-tyo-yrittaminen/pull/120 which includes the fix.
> UHF-6692: Add language content config for tpr_ontology_word_details

- composer.json
To test this:
1. Attempt to run `composer require drupal/helfi_api_base:dev-UHF-7265` in any project using TPR
2. Composer should fail to `Your requirements could not be resolved to an installable set of packages.` error
3. Update TPR module `composer require drupal/helfi_tpr:dev-UHF-7276`
4. Re-run step 1 and make sure API base is installed
> UHF-7276: Changed version constraint to work with any branches

- composer.json
- config/language/fi/views.view.service_units.yml
- config/language/fi/views.view.unit_services.yml
- config/language/sv/views.view.service_units.yml
- config/language/sv/views.view.unit_services.yml
- config/optional/views.view.service_units.yml
- config/optional/views.view.unit_services.yml
* Removed references to views_infinite_scroll from the module.
* Check installation instructions from https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/433
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/433
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/542
* https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/134
[UHF-7298]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-7298 Remove infinite scroll

- helfi_tpr.tokens.inc
- src/Entity/Service.php
* Add token for TPR Service description so that it can be used for metatag description
* `make fresh`
* Update the helfi_tpr
* `composer require drupal/helfi_platform_config:dev-UHF-8018_tpr_service_metatag_description_fix`
[UHF-8018]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8018: Fix for TPR Service metatag description

- helfi_tpr.info.yml
- modules/helfi_address_search/helfi_address_search.info.yml
- modules/helfi_school_addons/helfi_school_addons.info.yml
- src/Field/Connection/OpeningHour.php
- src/Field/FieldDefinition.php
- tests/modules/helfi_tpr_test/helfi_tpr_test.info.yml
- `composer require drupal/helfi_tpr:dev-UHF-7334`
- Open some TPR unit with opening hours, for example: `/tpr-unit/31791`.
- Make sure newlines (\n) are converted into html tags (`<br>` and `<p>`)
It should look something like: 
Compared to: 
where everything is mushed together.
> UHF-7334: Run opening hour content through _filter_autop to format it properly

- modules/helfi_school_addons/src/Plugin/views/filter/SchoolDetailsBase.php
- modules/helfi_school_addons/src/Plugin/views/filter/StudyProgrammeType.php
Called on content pages. TYPE_CONTENT required.
Go to `/fi/kasvatus-ja-koulutus/lukiokoulutus/lukiot`. Content is now shown based on content language.
> UHF-8290 getCurrentLanguage parameter 

- modules/helfi_address_search/src/Plugin/views/filter/AddressSearch.php
This PR adds `&municipality=Hhelsinki` to the unit address search.
* Make sure your kasko instance is up and running on latest dev branch (SOTE for example).
* `make fresh`
* Update the Helfi TPR module
* `composer require drupal/drupal-module-helfi-tpr:dev-UHF-8430-Unit-search-municipality-bug`
* Open https://helfi-kasko.docker.so/fi/kasvatus-ja-koulutus/varhaiskasvatus/varhaiskasvatus-paivakodissa/etsi-kunnallisia-paivakoteja and search for "Mannerheimintie 1" and check the first result. It should be rather close, not far like 80km away.
[UHF-8430]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8430: Added municipality to the address search query.

- modules/helfi_address_search/src/Plugin/views/area/AddressSearchInfo.php
- modules/helfi_address_search/src/Plugin/views/filter/AddressSearch.php
Reproduce bug:
- Setup kasko with make fresh
- Go to `https://helfi-kasko.docker.so/fi/kasvatus-ja-koulutus/varhaiskasvatus/varhaiskasvatus-paivakodissa/etsi-kunnallisia-paivakoteja?address_search=2022`
- run `docker logs helfi-kasko-app` (or go check the kasko app logs from docker desktop)
- You should see the error with `address_search_succeed`
Test fix:
- (if you didn't reproduce the bug:) Setup kasko with make fresh 
- Run `composer require drupal/helfi_tpr:dev-UHF-7748_tpr_error`
- Run `make drush-cr`
- Go to `https://helfi-kasko.docker.so/fi/kasvatus-ja-koulutus/varhaiskasvatus/varhaiskasvatus-paivakodissa/etsi-kunnallisia-paivakoteja?address_search=2022`
- run `docker logs helfi-kasko-app`(or go check the kasko app logs from docker desktop)
- You should not see any errors
- Page …
> UHF-7748: throws error because of missing # from the array key

- helfi_tpr.install
- migrations/tpr_unit.yml
- src/Entity/Listing/ListBuilder.php
- src/Entity/Unit.php
- src/Field/Connection/Link.php
- src/Field/Connection/OpeningHour.php
- src/Field/Connection/OpeningHourObject.php
- src/Field/Connection/OtherInfo.php
- src/Field/Connection/PhoneOrEmail.php
- src/Field/Connection/Price.php
- src/Field/Connection/Repository.php
- src/Field/Connection/TextWithLink.php
- src/Field/Connection/TextWithLinkBase.php
- src/Plugin/Field/FieldFormatter/ConnectionFormatter.php
- tests/src/Unit/ConnectionTest.php
- translations/fi.po
- translations/sv.po
Units are missing multiple fields from TPR.
- Added four missing fields to unit entities (charges, further informations, web sites, other contact information)
* Make sure your `kuva` instance is up and running on latest dev branch.
* `make fresh`
* Update the Helfi TPR config
* `composer require drupal/helfi_tpr:dev-UFH-8595_missing-unit-tpr-fields`
* `composer require drupal/hdbt:dev-UHF-8595_missing-tpr-fields`
* `composer require drupal/helfi_platform_config:dev-UHF-8595_tpr-unit-config-updates`
* Run `make drush-updb drush-cr drush-local-update`
* Run the migration `drush migrate:import tpr_unit --idlist 41047:fi,41047:sv,41047:en --update`
Check also the other PRs which updates the unit template and display configs: …
> UFH-8595: Added multiple missing fields to Units

- src/Entity/Unit.php
SonarCloud Quality Gate fails because of duplicated code.
Refactored the code to reduce duplicated code.
* Make sure your `kuva` instance is up and running on latest dev branch.
* `make fresh`
* Update the Helfi TPR config
* `composer require drupal/helfi_tpr:dev-UHF-8595_fix-duplicate-code`
* Run `make drush-updb drush-cr drush-locale-update`
* Run the migration `drush migrate:import tpr_unit --idlist 41047:fi,41047:sv,41047:en --update`
> UHF-8595: Fixed duplicated code

- modules/helfi_address_search/helfi_address_search.module
- Fixed the NULL types from `views_pre_execute` causing the `Cannot assign null to property Drupal\views\Plugin\views\query\QueryPluginBase:: of type int`.
- See: https://www.hel.fi/fi/test-kasvatus-ja-koulutus/varhaiskasvatus/varhaiskasvatus-paivakodissa/etsi-kunnallisia-paivakoteja
> UHF-9113: Drupal10 bug fixes

- modules/helfi_address_search/src/Plugin/views/filter/AddressSearch.php
* Issue from #kuuma_linja: after-school activity search results contain cached distances.
* Make sure your **KASKO** instance is up and running on latest dev branch.
* `make fresh`
* Update the TPR module
* `composer require drupal/helfi_tpr:dev-UHF-X-address-search-caching`
* Make sure that your `settings.local.php` and `*.services.yml` do not override default cache settings.
* Run `make drush-updb drush-cr`
> UHF-X: Fix caching issue in address search

- modules/helfi_address_search/src/Plugin/views/filter/AddressSearch.php
- tests/src/Functional/ServiceTranslationTest.php
- tests/src/Functional/UnitTranslationTest.php
* Fix address search caching for translations. There was an attempt to fix this earlier, but it did not work for translated content.
From #helfi_kuuma_linja
> Ruotsin- ja englanninkielisillä hakusivuilla (linkit alla) virhe on vielä siten, että kaikissa tuloskorteissa ei näy etäisyys annettuun osoitteeseen. Suomenkielisessä haussa näyttäisi toimivan.
[https://www.hel.fi/sv/fostran-och-utbildning/grundlaggande-utbildning/morgon-och-e[…]lorna/eftermiddagsverksamhet/platser-med-eftermiddagsverksamhet](https://www.hel.fi/sv/fostran-och-utbildning/grundlaggande-utbildning/morgon-och-eftermiddagsverksamhet-klubbar-och-hobbyer-i-skolorna/eftermiddagsverksamhet/platser-med-eftermiddagsverksamhet)
[https://www.hel.fi/en/childhood-and-education/basic-education/morning-and-after-sc[…]hobbies/after-sc …
> UHF-9454: Fix address search caching for translated entities [part 2]

- modules/helfi_address_search/src/Plugin/views/filter/AddressSearch.php
Allow using swedish street name on search field in finnish page vice versa
* git pull origin dev
* make fresh
* Update the Helfi-TPR
* composer require drupal/helfi_tpr:dev-UHF-9234
* Run make drush-updb drush-cr
- Go to [/fi/kasvatus-ja-koulutus/perusopetus/aamu-ja-iltapaivatoiminta-kerhot-ja-harrastukset/iltapaivatoiminta/iltapaivatoimintapaikat](https://helfi-kasko.docker.so/fi/kasvatus-ja-koulutus/perusopetus/aamu-ja-iltapaivatoiminta-kerhot-ja-harrastukset/iltapaivatoiminta/iltapaivatoimintapaikat)
- Change language to swedish and check out some street names
- Switch back to finnish and try searching based on the street names you saw on swedish side
- You should get results while using swedish street name on finnish …
> UHF-9234: Multilingual street address search instead of search with current language

- composer.json
- helfi_tpr.install
- helfi_tpr.links.menu.yml
- helfi_tpr.links.task.yml
- src/Entity/BaseFieldTrait.php
- src/Entity/Channel.php
- src/Entity/Unit.php
- `composer require drupal/helfi_tpr:dev-UHF-8908`
- `composer require drupal/helfi_api_base:dev-UHF-8908`
- Run `drush updb`
- Re-run TPR unit and service channel migrate: `drush migrate:import tpr_unit`, `drush migrate:import tpr_service_channel`
- Make sure email field is populated
* https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/171
* https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/155
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/928
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/717
> UHF-8908: Convert email field type to email

- translations/fi.po
Updated translations based on strategia-instance UI translation changes.
> UHF-9088: Translations

- src/Entity/Unit.php
- tests/src/Kernel/UnitEntityTest.php
If TPR-unit had any other provided language than fi, en or sv, the tpr unit page would whitescreen.
- Removed the provided-language template with logic in it
- Moved the logic to TPR-entity
- Called the entity method to get list of translated language names
- Setup Strategia-site
- [Go to this page](https://helfi-strategia.docker.so/fi/paatoksenteko-ja-hallinto/business-helsinki), it should whitescreen 
* `make fresh`
* Update the HDBT theme
* `composer require drupal/hdbt:dev-UHF-X_provided_language_whitescreen`
* Update the TPR module
* `composer require drupal/helfi_tpr:dev-UHF-X_provided_language_whitescreen`
- [Go to this …
> Uhf x provided language whitescreen

- helfi_tpr.module
- helfi_tpr.services.yml
- src/Event/MigrationPrepareRowEvent.php
- src/EventSubscriber/MigrationPrepareRowSubscriber.php
- tests/src/Kernel/MigrationPrepareRowSubscriberTest.php
* Fix the issue where TPR translations are not migrated
* `make fresh`
* Update the Helfi TPR module
* `composer require drupal/helfi_tpr:dev-UHF-11379`
* Run `make drush-updb drush-cr`
[UHF-11379]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11379: Fix missing translations in TPR migrations

- src/Entity/ErrandService.php
Check the [hdbt-pr](https://github.com/City-of-Helsinki/drupal-hdbt/pull/1349)
Users aren't supposed to be able to enter the entity's view route.
> UHF-12075 Remove errand service canonical route
