- config/install/system.action.tpr_unit_update_action.yml
- config/install/views.view.tpr_unit_list.yml
- config/optional/views.view.tpr_unit_list.yml
- src/Entity/Unit.php
- src/Plugin/migrate/destination/Tpr.php
- src/Plugin/migrate/source/Tpr.php
- tests/src/Functional/TprUnitListTest.php
To test this:
- Run `drush mim tpr_update --limit=100`
- Go to Content -> TPR - Unit
- Change title (or any other field) of any entity and save it
- Select the changed entity from the list (check checkbox)
- Click "Apply to selected items" and make sure the title is same as what it was before updating the entity manually
> UHF-162: Actions to mass update TPR entities manually

- config/install/migrate_plus.migration.tpr_unit.yml
- src/Entity/Unit.php
- src/Plugin/Field/FieldFormatter/ServiceMapFormatter.php
- tests/src/Unit/ServiceMapFormatterTest.php
To test this:
- drush pmu helfi_tpr && drush en helfi_tpr
- drush mim tpr_unit --limit=10
- Go to Content -> TPR - Unit and view any entity
- Make sure that service map is visible
> UHF-27: Map integration

- helfi_tpr.install
- migrations/tpr_unit.yml
- src/Entity/Unit.php
To test this:
- `composer require drupal/helfi_tpr:dev-UHF-1217`
- `drush updb`
- `drush cr`
- Migrate unit entities (`MIGRATE_LIMIT=500 drush mim tpr_unit` for example)
> UHF-1217: Picture url field

- config/install/system.action.tpr_service_update_action.yml
- config/language/fi/views.view.tpr_service_list.yml
- config/language/fi/views.view.tpr_unit_list.yml
- config/optional/views.view.tpr_service_list.yml
- config/optional/views.view.tpr_unit_list.yml
- helfi_tpr.install
- tests/src/Functional/TprUnitListTest.php
Check instructions from https://github.com/City-of-Helsinki/drupal-helfi/pull/105
> UHF-1478 TPR lists

- config/language/fi/views.view.service_units.yml
- config/optional/views.view.service_units.yml
- config/optional/views.view.unit_services.yml
https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/92
> UHF-1549 TPR entity fixes

- templates/tpr-service.html.twig
- templates/tpr-unit.html.twig
https://github.com/City-of-Helsinki/drupal-helfi/pull/119
https://github.com/City-of-Helsinki/drupal-hdbt/pull/89
https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/95
> UHF-1046 Unit search layout

- templates/tpr-service.html.twig
- templates/tpr-unit.html.twig
Instructions: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/96
> UHF-1550 Content areas

- templates/tpr-accessibility-sentences.html.twig
- templates/tpr-unit.html.twig
Check instructions: https://github.com/City-of-Helsinki/drupal-hdbt/pull/101
> UHF-1597: Accessibility

- src/Plugin/Field/FieldFormatter/ServiceMapFormatter.php
- templates/tpr-unit.html.twig
- tests/src/Unit/ServiceMapFormatterTest.php
Testing instructions are here: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/108
Also check these PRs:
https://github.com/City-of-Helsinki/drupal-hdbt/pull/103
https://github.com/City-of-Helsinki/drupal-helfi/pull/135
https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/24
https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/16
> UHF-1083 Unit map

- config/optional/views.view.tpr_service_list.yml
How to test:
- Check that Service list view can be sorted by updated date
> Updated TPR Service list updated time field.

- templates/tpr-service.html.twig
- templates/tpr-unit.html.twig
Instructions on how to test these fixes are written here: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/132
Also check these PRs:
https://github.com/City-of-Helsinki/drupal-helfi/pull/163
https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/49
https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/39
https://github.com/City-of-Helsinki/drupal-hdbt/pull/128
> UHF-2005 General fixes

- helfi_tpr.module
- templates/tpr-errand-service.html.twig
- templates/tpr-service-channel.html.twig
- templates/tpr-service.html.twig
Templates for TPR Service (Palvelusivu) pages.
> UHF-1410: palvelusivu

- templates/tpr-unit.html.twig
Testing instructions can be found here: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/138
Check also these PRs:
https://github.com/City-of-Helsinki/drupal-hdbt/pull/134
https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/62
https://github.com/City-of-Helsinki/drupal-helfi/pull/174
https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/62
https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/59
https://github.com/City-of-Helsinki/drupal-helfi-strategia/pull/10
> UHF-1181 Content liftup

- templates/tpr-errand-service.html.twig
- templates/tpr-service-channel.html.twig
- templates/tpr-service.html.twig
How to test:
1. Make sure you have imported services, errand services and service channels from TPR.
2.  If you have them already just skip to part 9. If not run `make shell`
3. `drush en -y helfi_tpr_config`
4. Import some TPR entities (set `MIGRATE_LIMIT=500 `or similar if seen fit):
5. `drush migrate:import tpr_service`
6. `drush migrate:import tpr_errand_service`
7. `drush migrate:import tpr_service_channel`
8. `drush cr` Now you should have some services and errand services and service channels.
9. Checkout out required branches for your local: `composer require drupal/helfi_tpr:dev-UHF-2085_errand_service_and_service_channel_layout && composer require drupal/helfi_hdbt:dev-UHF-2085_errand_service_and_service_channel_layout`
10. Go to view a service - for example: …
> UHF-2085 Errand service and service channel layout

- config/optional/views.view.unit_services.yml
- templates/tpr-service.html.twig
Check instructions from: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/145
> UHF-2088 Service list

- templates/tpr-service.html.twig
Check instructions from: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/149
> UHF-1736 Sidebar content

- templates/tpr-service-channel.html.twig
Instructions are written here: https://github.com/City-of-Helsinki/drupal-hdbt/pull/149
> UHF-2498: Service channel layout

- templates/tpr-unit.html.twig
Check instructions from here: https://github.com/City-of-Helsinki/drupal-hdbt/pull/155
> UHF-2694: Layout fixes

- templates/tpr-unit.html.twig
Testing instructions: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/176
Also check these:
https://github.com/City-of-Helsinki/drupal-hdbt/pull/158
https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/110
https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/103
https://github.com/City-of-Helsinki/drupal-helfi-strategia/pull/57
https://github.com/City-of-Helsinki/drupal-helfi/pull/197
> UHF-2699: Remove phone from unit teasers and generalize layout

- config/language/sv/views.view.service_units.yml
- config/optional/views.view.service_units.yml
- templates/tpr-unit.html.twig
Check instructions from: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/190
> UHF-2511 Translations

- templates/tpr-service.html.twig
Check instructions from https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/211
> UHF-1735 Table of contents

- helfi_tpr.install
- helfi_tpr.module
- src/Entity/Unit.php
- templates/tpr-unit.html.twig
Relates to https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/23
> UHF-3453: option to hide description on TPR Units

- templates/tpr-service-channel.html.twig
Please see: https://github.com/City-of-Helsinki/drupal-hdbt/pull/209
Related: [HDBT](https://github.com/City-of-Helsinki/drupal-hdbt/pull/209), [SOTE](https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/251)
> Add notice about template being overridden by HDBT theme

- helfi_tpr.module
- helfi_tpr.permissions.yml
Check instructions from https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/229
> UHF-3479 Read only role

- migrations/tpr_service.yml
Reverts City-of-Helsinki/drupal-module-helfi-tpr#71
> Revert "UHF-3152: combine errand_services and exact_errand_services fields"

- composer.json
See https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/242
> UHF-X Views infinite scroll update

- helfi_tpr.info.yml
- helfi_tpr.install
- helfi_tpr.module
- src/Entity/Unit.php
- templates/tpr-unit.html.twig
- translations/fi.po
- translations/sv.po
- added `show_www` field to TPR Unit entity
- moved TPR related translations from `helfi_platform_config`
> UHF-3821: 'Show website link' checkbox for TPR Unit edit form

- helfi_tpr.module
- src/Plugin/views/relationship/TagOwdRelationship.php
- src/TprViewsData.php
Reverts City-of-Helsinki/drupal-module-helfi-tpr#119
> Revert "Revert "UHF-5473: Group ontology word details relationship results""

- modules/helfi_address_search/src/Plugin/views/filter/AddressSearch.php
- added `language` parameter to the address search so that the unit (daycare) search returns results also with Swedish street names
1. set up KASKO instance
2. get this branch of the `helfi_tpr` module: `composer require drupal/helfi_tpr:dev-UHF-6298_daycare_search_language_parameter`
3. clear cache: `make drush-cr`
1. create a landing page in Finnish and add "Päiväkotihaku" paragraph on it
2. use the search with some address, for example "josafatinkatu 11" and see the list of results in Finnish
3. add a Swedish translation for the page
4. on that page, use the search using a Swedish street name of the same address, for example "josafatsgatan 11" and see that the search returns the same results but in Swedish
> UHF-6298: Address search language parameter

- README.md
Updated the contact email in the README.md. Nothing to test, just sanity check.
[UHF-8133]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update contact email in README.md

- translations/fi.po
- translations/sv.po
- Added translations for TPR unit fields.
> UHF-8135: Added translations for TPR unit fields.

- src/Entity/OntologyWordDetails.php
* Fix deprecated code (https://www.drupal.org/node/3201242)
* `make fresh`
* Update the Helfi tpr
* `composer require drupal/helfi_tpr:dev-UHF-9113-drupal-10-support`
* Run `make drush-updb drush-cr`
* Link to other PR
[UHF-9113]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9113: Drupal 10 support

- modules/helfi_school_addons/helfi_school_addons.info.yml
Remove remaining code of previously uninstalled module helfi_school_addons
> UHF-X: remove uninstalled module helfi_school_addons for good.
